-- Oracle DB Schema Definition for GeM Procurement Platform (SIH 26100)

CREATE TABLE gem_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    role VARCHAR2(30) NOT NULL,
    organization_name VARCHAR2(150),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gem_tenders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tender_number VARCHAR2(50) UNIQUE NOT NULL,
    title VARCHAR2(255) NOT NULL,
    department VARCHAR2(150) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    estimated_value NUMBER(18, 2) NOT NULL,
    min_turnover NUMBER(18, 2) NOT NULL,
    min_experience_years NUMBER(5, 1) NOT NULL,
    required_certs_json CLOB,
    submission_deadline TIMESTAMP NOT NULL,
    status VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_by VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gem_tender_rules (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tender_id NUMBER NOT NULL REFERENCES gem_tenders(id),
    rule_name VARCHAR2(100) NOT NULL,
    rule_category VARCHAR2(50) NOT NULL,
    condition_expression VARCHAR2(255) NOT NULL,
    weight NUMBER(5, 2) DEFAULT 1.0,
    is_mandatory NUMBER(1) DEFAULT 1,
    pass_criterion VARCHAR2(255)
);

CREATE TABLE gem_bid_submissions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_number VARCHAR2(50) UNIQUE NOT NULL,
    tender_id NUMBER NOT NULL REFERENCES gem_tenders(id),
    bidder_id VARCHAR2(50) NOT NULL,
    bidder_name VARCHAR2(150) NOT NULL,
    pan VARCHAR2(10) NOT NULL,
    gstin VARCHAR2(15) NOT NULL,
    declared_turnover NUMBER(18, 2),
    declared_experience NUMBER(5, 1),
    submission_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(30) DEFAULT 'RECEIVED' NOT NULL,
    appeal_status VARCHAR2(30) DEFAULT 'NONE'
);

CREATE TABLE gem_bid_documents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_id NUMBER NOT NULL REFERENCES gem_bid_submissions(id),
    document_type VARCHAR2(50) NOT NULL,
    filename VARCHAR2(255) NOT NULL,
    storage_path VARCHAR2(500) NOT NULL,
    file_hash VARCHAR2(64) NOT NULL,
    ocr_text CLOB,
    extracted_turnover NUMBER(18, 2),
    extracted_experience NUMBER(5, 1),
    extracted_certs_json CLOB,
    is_tampered NUMBER(1) DEFAULT 0,
    tamper_score NUMBER(5, 3) DEFAULT 0.0,
    tamper_reason VARCHAR2(500),
    is_duplicate NUMBER(1) DEFAULT 0,
    duplicate_matched_bidder VARCHAR2(50)
);

CREATE TABLE gem_identity_verifications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_id NUMBER UNIQUE NOT NULL REFERENCES gem_bid_submissions(id),
    pan VARCHAR2(10) NOT NULL,
    pan_status VARCHAR2(30) NOT NULL,
    pan_holder_name VARCHAR2(150),
    pan_verification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gstin VARCHAR2(15) NOT NULL,
    gst_status VARCHAR2(30) NOT NULL,
    gst_legal_name VARCHAR2(150),
    name_mismatch_flag NUMBER(1) DEFAULT 0,
    is_debarred NUMBER(1) DEFAULT 0,
    debarment_agency VARCHAR2(100),
    debarment_reason VARCHAR2(255),
    overall_identity_status VARCHAR2(30) NOT NULL
);

CREATE TABLE gem_compliance_scores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_id NUMBER UNIQUE NOT NULL REFERENCES gem_bid_submissions(id),
    tender_id NUMBER NOT NULL REFERENCES gem_tenders(id),
    total_score NUMBER(5, 2) NOT NULL,
    risk_level VARCHAR2(20) NOT NULL,
    drools_trace_json CLOB,
    shap_attribution_json CLOB,
    evaluated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gem_officer_decisions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_id NUMBER UNIQUE NOT NULL REFERENCES gem_bid_submissions(id),
    tender_id NUMBER NOT NULL REFERENCES gem_tenders(id),
    officer_id VARCHAR2(50) NOT NULL,
    decision VARCHAR2(30) NOT NULL,
    ai_score NUMBER(5, 2),
    officer_override NUMBER(1) DEFAULT 0,
    written_justification CLOB,
    decided_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gem_audit_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR2(50) NOT NULL,
    entity_type VARCHAR2(50) NOT NULL,
    entity_id VARCHAR2(50) NOT NULL,
    actor_username VARCHAR2(50) NOT NULL,
    actor_role VARCHAR2(30) NOT NULL,
    action_description VARCHAR2(500) NOT NULL,
    previous_state_json CLOB,
    new_state_json CLOB,
    integrity_hash VARCHAR2(64) NOT NULL,
    previous_hash VARCHAR2(64),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gem_grievance_appeals (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_id NUMBER NOT NULL REFERENCES gem_bid_submissions(id),
    bidder_id VARCHAR2(50) NOT NULL,
    appeal_reason CLOB NOT NULL,
    additional_evidence_path VARCHAR2(500),
    officer_response CLOB,
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP
);

-- Indices for performance
CREATE INDEX idx_tenders_status ON gem_tenders(status);
CREATE INDEX idx_bids_tender_id ON gem_bid_submissions(tender_id);
CREATE INDEX idx_bids_status ON gem_bid_submissions(status);
CREATE INDEX idx_audit_integrity ON gem_audit_logs(integrity_hash);
